name: SC3040

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/src
      - /src/node_modules
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8080
      - NEXT_PUBLIC_RECEIPT_SERVICE_URL=http://localhost:8081
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/next.config.js
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /src
          action: sync
    command: npm run dev

# TODO:
#  backend:

  receipt-service:
    build:
      context: ./microservices/receiptService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./microservices/receiptService:/app
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    develop:
      watch:
        - path: ./microservices/receiptService
          target: /app
          action: sync


# Start Running:
# 1) docker compose up

# Start Running (with rebuild):
# 1) docker compose up --build

# Stop Running:
# 1) Ctrl C
# 2) docker compose down