name: SC3040

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/src
      - /src/node_modules
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8080
      - NEXT_PUBLIC_RECEIPT_MODEL_URL=http://localhost:8080
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/next.config.js
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /src
          action: sync
    command: npm run dev

  microservices:
    build:
      context: ./microservices
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./microservices:/app
      - ${HOME}/Downloads:/app/downloads
    environment:
      - FLASK_ENV=development
    develop:
      watch:
        - path: ./microservices
          target: /app
          action: sync


# Start Running:
# 1) docker compose up

# Stop Running:
# 1) Ctrl C
# 2) docker-compose down