services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/src
      - /src/node_modules
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://app:8080
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    command: npm run dev

# Start Running:
# 1) docker-compose up --build

# Stop Running:
# 1) Ctrl C
# 2) docker-compose down