import { ApiProperty } from '@nestjs/swagger';

export class UserResponseDto {
  @ApiProperty({
    description:
      'Unique identifier of the user, automatically generated by database',
    example: '650c59a88f1e78c88102d1a4',
  })
  readonly id: string;
  @ApiProperty({ description: 'Unique username of the user', example: 'user' })
  readonly username: string;
  @ApiProperty({
    description: 'Email of the user',
    example: 'user@example.com',
  })
  readonly email: string;
  @ApiProperty({ description: 'First name of the user', example: 'Mike' })
  readonly firstName: string;
  @ApiProperty({ description: 'Last name of the user', example: 'Ross' })
  readonly lastName: string;
  @ApiProperty({
    description:
      'Base64 encoded profile image that can be displayed on the frontend with img tag src attribute',
  })
  image: string;
  @ApiProperty({
    description: 'Security question for password recovery',
    example: 'What was the name of your first pet?',
  })
  readonly securityQuestion: string;
}
