global:
  scrape_interval: 15s

scrape_configs:
  # Scrape Prometheus
  - job_name: 'prometheus'
    static_configs:
    - targets: [ 'prometheus:9090' ]

  # Scrape NestJS metrics
  - job_name: 'nestjs'
    static_configs:
      - targets: ['backend:8080']

  # Scrape MongoDB Exporter metrics
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']  # MongoDB Exporter metrics